export const dataTestimonials = [
  {
    id: 1,
    name: "Golden_Trades",
    date: "2024-07-08",
    bank: "BankRepublicUruguay",
    testimonial: "Un Genial Rol!!",
  },
  {
    id: 2,
    name: "fa*****.com",
    date: "2024-07-09",
    bank: "BankRepublicUruguay",
    testimonial: "excelente como siempre!!, Transaccion rapida, Educado y amable, Seguro y confiable, Buen Precio",
  },
  {
    id: 3,
    name: "dg*****.com",
    date: "2024-07-05",
    bank: "Prex",
    testimonial: "Transaccion rapida, Educado y amable, Seguro y confiable, Buen Precio. Todo excelente, mi trader de confianza!",
  },
  {
    id: 4,
    name: "ra*****.com",
    date: "2024-06-16",
    bank: "Prex",
    testimonial: "Excelente vendedonr, todo de 10. Rapido y confiable, lo recomiendo!!",
  },
  {
    id: 5,
    name: "ca*****.com",
    date: "2024-06-20",
    bank: "Prex",
    testimonial: "Transaccion rapida, Educado y amable, Paciente Super seguro todo",
  },
  {
    id: 6,
    name: "gu*****.com",
    date: "2024-06-24",
    bank: "ItauUruguay",
    testimonial: "Excelente atencion por parte de la empresa y su personal muy profecional.",
  },
  {
    id: 7,
    name: "MarioCripto26",
    date: "2024-06-12",
    bank: "SantanderUrug",
    testimonial: "Muy amable y clara, Seguridad y confianza",
  },
];
